#!/bin/bash
# =============================================================================
# RunPod: Vocalido V1 — RESUME from step 87,000 → 160,000
# -----------------------------------------------------------------------------
# Run this ENTIRE script in RunPod terminal (Ubuntu + NVIDIA GPU)
# Prerequisites: RunPod pod with PyTorch image, internet access
# Estimated time: ~4-6 hours on A100 / ~8-10 hours on RTX 3090
# =============================================================================

set -e
echo "🎤 Vocalido V1 — Resume Training (87k → 160k)"
echo "================================================"

WORKSPACE="/workspace/DiffSinger"
EXP_NAME="vocalido_v1_runpod"
GCS_DATA="gs://vocalido-master-corpus-v1/diffsinger/data/vocalido"
GCS_CKPT="gs://vocalido-master-corpus-v1/diffsinger/checkpoints"
GCS_OUT="gs://vocalido-master-corpus-v1/output/vocalido_v1"

# ── 1. Install gcloud SDK ─────────────────────────────────────────────────────
if ! command -v gsutil &> /dev/null; then
    echo "📦 Installing gcloud SDK..."
    curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts
    source ~/.bashrc
    export PATH="$HOME/google-cloud-sdk/bin:$PATH"
fi

echo "🔑 Authenticate GCS (paste service account JSON key when prompted)"
echo "   Or skip if already authenticated."
read -p "Press ENTER to continue (or auth first)..."

# ── 2. Setup workspace ────────────────────────────────────────────────────────
mkdir -p $WORKSPACE && cd $WORKSPACE

if [ ! -f "run.py" ]; then
    echo "📥 Cloning DiffSinger..."
    git clone https://github.com/openvpi/DiffSinger.git .
fi

echo "📦 Installing Python dependencies..."
pip install -q -r requirements.txt
pip install -q librosa soundfile

# ── 3. Download dataset from GCS ─────────────────────────────────────────────
echo ""
echo "📥 Downloading FULL dataset (73 recordings, all phonemes)..."
mkdir -p data/vocalido
gsutil -m rsync -r "$GCS_DATA" data/vocalido/
echo "✅ Dataset ready:"
wc -l data/vocalido/transcriptions.csv
ls data/vocalido/wavs/ | wc -l && echo "WAV files"

# ── 4. Download checkpoints ───────────────────────────────────────────────────
echo ""
echo "📥 Downloading checkpoints..."

# Base model (for config reference)
mkdir -p checkpoints/base_model
gsutil -m cp "$GCS_CKPT/base_model/base_model.ckpt" checkpoints/base_model/ || \
    echo "⚠️  base_model not in GCS (ok if only resuming)"

# 87k checkpoint to RESUME from
mkdir -p "checkpoints/$EXP_NAME"
gsutil -m cp "$GCS_CKPT/$EXP_NAME/model_ckpt_steps_87000.ckpt" \
    "checkpoints/$EXP_NAME/" || {
    echo "❌ 87k checkpoint not in GCS!"
    echo "   Upload from Mac first:"
    echo "   gsutil cp /path/to/model_ckpt_steps_87000.ckpt $GCS_CKPT/$EXP_NAME/"
    exit 1
}

# Copy config.yaml
gsutil cp "$GCS_CKPT/$EXP_NAME/config.yaml" \
    "checkpoints/$EXP_NAME/config.yaml" || \
    echo "⚠️  config.yaml not found in GCS"

# Vocoder (NSF-HifiGAN)
mkdir -p checkpoints/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02
gsutil -m cp -r \
    "$GCS_CKPT/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/" \
    checkpoints/ 2>/dev/null || echo "⚠️  Vocoder check manually"

# PE model (RMVPE)
mkdir -p checkpoints/rmvpe
gsutil -m cp "$GCS_CKPT/rmvpe/model.pt" checkpoints/rmvpe/ 2>/dev/null || true

echo "✅ Checkpoints ready"

# ── 5. Write training config ──────────────────────────────────────────────────
cat > config_vocalido_v1_resume.yaml << 'YAML'
# Vocalido V1 — Resume config (87k → 160k)
# Generated by runpod_resume_87k.sh

K_step: 400
K_step_infer: 400
T_start: 0.4
T_start_infer: 0.4
audio_num_mel_bins: 128
audio_sample_rate: 44100
backbone_args:
  dropout_rate: 0.0
  kernel_size: 31
  num_channels: 1024
  num_layers: 6
  strong_cond: true
backbone_type: lynxnet

binarization_args:
  num_workers: 4
  shuffle: true
binarizer_cls: preprocessing.acoustic_binarizer.AcousticBinarizer
binary_data_dir: data/vocalido_v1_bin

datasets:
- language: en
  raw_data_dir: data/vocalido
  speaker: vocalido
  spk_id: 0
  test_prefixes:
  - song_37

dictionaries:
  en: dictionaries/english.txt

diff_accelerator: ddim
diff_speedup: 10
diffusion_type: reflow

# ── Fine-tune from 87k checkpoint (RESUME) ───────────────────────────────────
finetune_enabled: true
finetune_ckpt_path: checkpoints/vocalido_v1_runpod/model_ckpt_steps_87000.ckpt
finetune_ignored_params: []        # empty = resume ALL weights (not re-init)
finetune_strict_shapes: true

hop_size: 512
hidden_size: 256

lr_scheduler_args:
  gamma: 0.75
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 10000

max_batch_frames: 50000
max_batch_size: 16
max_updates: 160000             # Train until step 160k

num_ckpt_keep: 5
permanent_ckpt_interval: 20000
permanent_ckpt_start: 100000

optimizer_args:
  beta1: 0.9
  beta2: 0.98
  lr: 0.0003                    # Lower LR for resume (was 0.0006 at start)
  optimizer_cls: torch.optim.AdamW
  weight_decay: 0

pe: parselmouth
pe_ckpt: checkpoints/rmvpe/model.pt

pl_trainer_accelerator: gpu
pl_trainer_devices: auto
pl_trainer_precision: 16-mixed

sampling_algorithm: euler
sampling_steps: 20

task_cls: training.acoustic_task.AcousticTask
use_shallow_diffusion: true
val_check_interval: 500
val_with_vocoder: false

vocoder: NsfHifiGAN
vocoder_ckpt: checkpoints/pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt

work_dir: checkpoints/vocalido_v1_runpod
YAML

echo "✅ Config written: config_vocalido_v1_resume.yaml"

# ── 6. Binarize dataset ───────────────────────────────────────────────────────
echo ""
echo "⚙️  Binarizing dataset (~5 min)..."
python run.py --config config_vocalido_v1_resume.yaml --stage binarize
echo "✅ Binarization complete!"

# ── 7. Resume training ────────────────────────────────────────────────────────
echo ""
echo "🚀 Resuming training from step 87,000..."
echo "   Target: 160,000 steps"
echo "   Checkpoints saved every 1,000 steps → checkpoints/vocalido_v1_runpod/"
echo ""

python run.py --config config_vocalido_v1_resume.yaml --stage train

echo ""
echo "✅ Training complete!"

# ── 8. Upload best checkpoint to GCS ─────────────────────────────────────────
echo "📤 Uploading trained checkpoints to GCS..."
gsutil -m rsync -r checkpoints/vocalido_v1_runpod/ "$GCS_OUT/"

echo ""
echo "🎉 Done! Model is at: $GCS_OUT/"
echo ""
echo "📥 Download to Mac:"
echo "   gsutil -m cp -r '$GCS_OUT/model_ckpt_steps_160000.ckpt' \\"
echo "     ~/vocamind-projects/Memolody_V2/vocalido_server/training/DiffSinger/checkpoints/vocalido_v1_runpod/"
