/**
 * SheetMusicOCR — Gemini Vision → MusicXML
 * -----------------------------------------
 * Supports: images (jpg/png/webp) and native PDF (multi-page).
 * Gemini 2.5 Flash natively handles application/pdf via inline_data.
 */

const IMAGE_MIME_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
const PDF_MIME_TYPE = 'application/pdf';

export interface OCRResult {
  xml: string;
  confidence: 'high' | 'medium' | 'low';
  message: string;
}

const OMR_IMAGE_PROMPT = `You are a world-class Music OMR (Optical Music Recognition) engine with 99.9% accuracy.
The user provides an image of a musical score (sheet music).

YOUR TASK: Convert the image into a VALID, COMPLETE MusicXML 4.0 document that is an EXACT replica of the printed score.

═══ ABSOLUTE RULES (VIOLATION = FAILURE) ═══

1. TIME SIGNATURE: Read the EXACT numbers printed after the clef/key signature.
   - If you see 2/4, output <beats>2</beats><beat-type>4</beat-type>. Do NOT change it to 4/4.
   - If you see 3/4, 6/8, 2/2, etc. — output EXACTLY what is printed. NEVER guess or default to 4/4.

2. KEY SIGNATURE: Count EVERY sharp/flat on the staff at the start:
   - 1♯ = <fifths>1</fifths> (G major)  |  2♯ = <fifths>2</fifths> (D major)
   - 1♭ = <fifths>-1</fifths> (F major) |  2♭ = <fifths>-2</fifths> (Bb major)

3. DO NOT INVENT: If chord symbols (Gmaj7, Cmaj7, etc.) are NOT printed on the score, do NOT add them.
   Only include <harmony> elements when chord symbols are visibly printed above the staff.

4. TITLE & COMPOSER: If a title is printed at the top, use it in <work-title>.
   If a composer name is printed, use it in <creator type="composer">.
   Do NOT output "Unknown Composer" if a name is visible.

5. TEMPO: Read the tempo marking printed on the score:
   - Andantino → <per-minute>76</per-minute>
   - Andante → <per-minute>72</per-minute>
   - Moderato → <per-minute>108</per-minute>
   - Allegro → <per-minute>132</per-minute>
   - If a specific ♩= number is printed, use that exact number.

6. NOTE ACCURACY:
   - Read each note's position on the staff line/space precisely for correct <step> and <octave>.
   - Accidentals (♯♭♮) printed on the score MUST appear as <alter>.
   - Dots after notes extend duration by 50%.

7. CHORDS: Notes stacked vertically (played simultaneously) MUST use <chord/> on all notes except the first.

8. GRAND STAFF (Piano): One <part> with two staves. Use <staff>1</staff> for treble, <staff>2</staff> for bass.
   Use <backup> to write the bass clef voice after treble within the same measure.

9. MEASURE DURATION: Note durations in each measure MUST sum to EXACTLY the time signature value.
   For 2/4: each measure = exactly 2 quarter-note beats.

OUTPUT FORMAT:
- Start IMMEDIATELY with: <?xml version="1.0" encoding="UTF-8"?>
- Use <score-partwise version="4.0"> as root.
- NO markdown fences. NO explanations. NO text outside the XML.

Start your response IMMEDIATELY with: <?xml`;

const OMR_PDF_PROMPT = `You are a world-class Music OMR engine with 99.9% accuracy.
The user provides a PDF of a musical score which may contain multiple pages.

YOUR TASK: Convert ALL pages into ONE VALID, COMPLETE MusicXML 4.0 document — an EXACT replica.

═══ ABSOLUTE RULES ═══

1. TIME SIGNATURE: Read the EXACT printed time signature. 2/4 means 2/4, NOT 4/4. Never guess.
2. KEY SIGNATURE: Count every sharp/flat precisely. 1♯ = <fifths>1</fifths>.
3. DO NOT INVENT chord symbols. Only include <harmony> if chord names are printed on the score.
4. TITLE & COMPOSER: Read from the score if visible. Do NOT write "Unknown".
5. TEMPO: Andantino=76, Andante=72, Moderato=108, Allegro=132. Use exact ♩= if printed.
6. Each note: correct <step>, <octave>, <alter>, <duration>, <type>. Dots = dotted duration.
7. Chords: <chord/> on all simultaneous notes except the first.
8. Piano grand staff = one <part> with two staves + <backup> between them.
9. Measure durations must sum to exactly the time signature.
10. Transcribe ALL pages maintaining correct measure numbering.

OUTPUT:
- Raw XML only. Start with: <?xml version="1.0" encoding="UTF-8"?>
- <score-partwise version="4.0"> root. NO markdown. NO explanations.

  Start your response IMMEDIATELY with: <?xml`;

const OMR_VERIFY_PROMPT = `You are a world-class Music Engraver performing FINAL quality control on an OMR result.

The user provides:
1. The ORIGINAL musical score image/PDF
2. A DRAFT MusicXML generated by a preliminary OMR engine

YOUR MISSION: Compare the draft XML against the original image and produce a 100% CORRECTED MusicXML.

═══ CHECK THESE IN ORDER (most critical first) ═══

✅ 1. TIME SIGNATURE: Is <beats> and <beat-type> EXACTLY what the score shows?
       Common OMR error: defaulting to 4/4 when the score shows 2/4, 3/4, 6/8, etc.
       FIX IT if wrong.

✅ 2. INVENTED HARMONIES: Does the draft contain <harmony> chord symbols (Gmaj7, Cmaj7, etc.)
       that are NOT printed on the original score? If so, DELETE them entirely.

✅ 3. TITLE & COMPOSER: Does <work-title> match the title on the score?
       Does <creator type="composer"> match the composer name on the score?
       FIX if wrong or missing.

✅ 4. TEMPO: Does <per-minute> match the tempo marking on the score?
       Andantino≈76, Andante≈72, Moderato≈108, Allegro≈132. FIX if wrong.

✅ 5. KEY SIGNATURE: Does <fifths> match the number of sharps/flats on the score?

✅ 6. NOTE PITCHES: For each measure, verify note <step> and <octave> match staff positions.
       Check accidentals (<alter>) against printed ♯♭♮.

✅ 7. CHORD TAGS: Simultaneous notes MUST have <chord/> on all except the first.

✅ 8. MEASURE DURATION: Durations must sum to exactly the time signature for every measure.

✅ 9. DYNAMICS & MARKINGS: Include <dynamics> (p, mf, f, etc.) if printed. Include ties/slurs.

OUTPUT RULES:
- Output ONLY raw XML starting with: <?xml version="1.0" encoding="UTF-8"?>
- <score-partwise version="4.0"> root. NO markdown. NO explanations. NO text outside XML.
- If the draft is already correct, output it unchanged.`;

// ─────────────────────────────── helpers ───────────────────────────────

/** Convert File to base64 data string (strips the data:...;base64, prefix) */
async function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.split(',')[1]);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

/** Get Gemini API key — vite.config.ts injects via define{} as process.env.* */
function getApiKey(): string {
  // vite.config.ts defines these at build time:
  //   'process.env.API_KEY': JSON.stringify(GEMINI_KEY)
  //   'process.env.GEMINI_API_KEY': JSON.stringify(GEMINI_KEY)
  // @ts-ignore
  const key = (process.env.GEMINI_API_KEY || process.env.API_KEY || '') as string;
  if (!key) throw new Error('GEMINI_API_KEY ไม่ได้ตั้งค่า กรุณาตรวจสอบไฟล์ .env');
  return key;
}

/** Call Gemini generateContent with the given content parts */
// Simple in‑memory cache for Gemini responses
const geminiCache = new Map<string, string>();
let lastGeminiCall = 0;
/**
 * Rate‑limited wrapper around the real Gemini call.
 * Guarantees at least 1500 ms between successive requests.
 */
async function rateLimitedCallGemini(parts: object[]): Promise<string> {
  const now = Date.now();
  const elapsed = now - lastGeminiCall;
  if (elapsed < 1500) {
    await new Promise(res => setTimeout(res, 1500 - elapsed));
  }
  lastGeminiCall = Date.now();
  return callGeminiVision(parts);
}

async function callGeminiVision(parts: object[]): Promise<string> {
  const cacheKey = JSON.stringify(parts);
  if (geminiCache.has(cacheKey)) {
    return geminiCache.get(cacheKey)!;
  }
  const apiKey = getApiKey();
  const modelsToTry = ['gemini-2.5-pro', 'gemini-2.0-flash'];
  let lastError = '';

  for (const modelName of modelsToTry) {
    const url = `https://generativelanguage.googleapis.com/v1/models/${modelName}:generateContent?key=${apiKey}`;
    let retries = 0;
    const maxRetries = 2;

    while (retries <= maxRetries) {
      try {
        console.log(`[Gemini] Attempting ${modelName} (Attempt ${retries + 1})...`);
        res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts }],
            generationConfig: {
              temperature: 0.05,
              maxOutputTokens: 32768
            },
          }),
          signal: AbortSignal.timeout(180000),
        });

        if (res.ok) {
          const data = await res.json();
          const rawText: string = data?.candidates?.[0]?.content?.parts?.[0]?.text || '';
          if (!rawText) throw new Error('Empty response from AI');
          geminiCache.set(cacheKey, rawText);
          return rawText;
        }

        const errorStatus = res.status;
        const isRetryable = errorStatus === 429 || errorStatus === 503 || errorStatus === 500;
        
        if (isRetryable && retries < maxRetries) {
          const waitTime = (retries + 1) * 3000;
          await new Promise(r => setTimeout(r, waitTime));
          retries++;
          continue;
        }

        const errData = await res.json().catch(() => ({ error: { message: res?.statusText } }));
        lastError = `${modelName}: ${errData?.error?.message || res.statusText}`;
        console.warn(`[Gemini] ${modelName} failed: ${lastError}`);
        break; // Try next model
      } catch (err: any) {
        if (err.name === 'AbortError' && retries < maxRetries) {
          retries++;
          continue;
        }
        lastError = err.message;
        break; // Try next model
      }
    }
  }

  throw new Error(`AI Engines exhausted. Last error: ${lastError}`);
}

/** Strip markdown fences and extract clean MusicXML block from Gemini response */
function extractXmlFromGeminiResponse(rawText: string): string {
  const text = rawText.replace(/^```(?:xml)?\s*/m, '').replace(/\s*```\s*$/m, '').trim();
  const xmlStart = text.indexOf('<?xml');
  const xmlEnd = text.lastIndexOf('</score-partwise>');
  if (xmlStart !== -1 && xmlEnd !== -1) return text.slice(xmlStart, xmlEnd + '</score-partwise>'.length);
  if (xmlStart !== -1) return text.slice(xmlStart);
  const altStart = text.indexOf('<score-partwise');
  if (altStart !== -1) return '<?xml version="1.0" encoding="UTF-8"?>\n' + text.slice(altStart);
  throw new Error('Gemini ไม่สามารถอ่านโน้ตได้ กรุณาลองภาพหรือ PDF ที่ชัดกว่านี้ครับ');
}

/** Auto-repair truncated XML when Gemini hits max tokens mid-document */
function repairTruncatedXml(xml: string): string {
  if (xml.includes('</score-partwise>')) return xml;
  const noteCount = (xml.match(/<note/g) || []).length;
  if (noteCount === 0) return xml;
  console.warn('[SheetMusicOCR] XML truncated — auto-repairing...');
  if (!xml.includes('</measure>') || xml.lastIndexOf('<measure') > xml.lastIndexOf('</measure>')) xml += '\n    </measure>';
  if (!xml.includes('</part>') || xml.lastIndexOf('<part') > xml.lastIndexOf('</part>')) xml += '\n  </part>';
  xml += '\n</score-partwise>';
  return xml;
}

// ─────────────────────────── public API ────────────────────────────────

/**
 * Recognize sheet music from an IMAGE file via Gemini Vision (single-pass, enhanced prompt)
 */
export async function recognizeSheetMusic(file: File): Promise<OCRResult> {
  if (!IMAGE_MIME_TYPES.includes(file.type) && !/\.(jpg|jpeg|png|webp)$/i.test(file.name)) {
    throw new Error(`ไม่รองรับไฟล์ประเภทนี้: ${file.type}. กรุณาใช้ JPG, PNG, หรือ WebP`);
  }

  console.log('[SheetMusicOCR] Image → Gemini Vision:', file.name, `(${(file.size / 1024).toFixed(0)}KB)`);

  const base64Data = await fileToBase64(file);
  const mimeType = (file.type || 'image/jpeg') as 'image/jpeg' | 'image/png' | 'image/webp';

  // ── PASS 1: Transcription ──
  const rawText = await rateLimitedCallGemini([
    { text: OMR_IMAGE_PROMPT },
    { inline_data: { mime_type: mimeType, data: base64Data } },
  ]);

  let xml = extractXmlFromGeminiResponse(rawText);
  xml = repairTruncatedXml(xml);

  // ── PASS 2: Verification & Repair (99% Accuracy goal) ──
  console.log('[SheetMusicOCR] ✅ Pass 1 Header detected. Starting Verification Pass...');
  const verifiedText = await rateLimitedCallGemini([
    { text: OMR_VERIFY_PROMPT },
    { text: `DRAFT XML TO REPAIR:\n${xml}` },
    { inline_data: { mime_type: mimeType, data: base64Data } },
  ]);

  let finalXml = extractXmlFromGeminiResponse(verifiedText);
  finalXml = repairTruncatedXml(finalXml);

  const noteCount = (finalXml.match(/<note/g) || []).length;
  const confidence: OCRResult['confidence'] = noteCount > 20 ? 'high' : noteCount > 5 ? 'medium' : 'low';
  console.log(`[SheetMusicOCR] ✅ 2nd Pass Success: ${noteCount} notes`);

  return { xml: finalXml, confidence, message: `Gemini 2.5 Pro (Dual-Pass 99% Mode) อ่านได้ ${noteCount} โน้ต` };
}

/**
 * Recognize sheet music from a PDF file via Gemini Vision (single-pass, enhanced prompt)
 * Gemini 2.5 Flash natively supports application/pdf — no page conversion needed.
 */
export async function recognizePDF(file: File): Promise<OCRResult> {
  if (!isPDFFile(file)) throw new Error('File is not a PDF');

  const sizeMB = file.size / (1024 * 1024);
  console.log(`[SheetMusicOCR] PDF → Gemini Vision: ${file.name} (${sizeMB.toFixed(1)}MB)`);

  if (sizeMB > 20) {
    throw new Error(
      `PDF ขนาด ${sizeMB.toFixed(1)}MB ใหญ่เกินไป (สูงสุด 20MB)\n` +
      `กรุณาลด resolution หรือตัดเฉพาะส่วนที่ต้องการครับ`
    );
  }

  const base64Data = await fileToBase64(file);

  const rawText = await rateLimitedCallGemini([
    { text: OMR_PDF_PROMPT },
    { inline_data: { mime_type: PDF_MIME_TYPE, data: base64Data } },
  ]);

  let xml = extractXmlFromGeminiResponse(rawText);
  xml = repairTruncatedXml(xml);

  const noteCount = (xml.match(/<note/g) || []).length;
  const confidence: OCRResult['confidence'] = noteCount > 50 ? 'high' : noteCount > 10 ? 'medium' : 'low';
  console.log(`[SheetMusicOCR] ✅ PDF: ${noteCount} notes`);

  return { xml, confidence, message: `Gemini อ่าน PDF ได้ ${noteCount} โน้ต` };
}

/**
 * FALLBACK: Local Audiveris OMR server (port 3003)
 */
export async function omrWithAudiveris(file: File): Promise<OCRResult> {
  const formData = new FormData();
  formData.append('image', file);

  const res = await fetch('http://localhost:3003/omr', {
    method: 'POST',
    body: formData,
    signal: AbortSignal.timeout(120000), // Increase to 120s for full pages
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: 'Audiveris error' }));
    throw new Error(err.error || `Audiveris error ${res.status}`);
  }

  const xml = await res.text();
  if (!xml.includes('<score-partwise')) throw new Error('Invalid MusicXML from Audiveris');

  // 🧪 Validation: Ensure we actually have measures
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xml, "text/xml");
  const measures = xmlDoc.getElementsByTagName("measure");
  if (measures.length === 0) {
    throw new Error("Audiveris อ่านภาพนี้สำเร็จแต่ไม่พบตัวโน้ตดนตรี กรุณาลองใช้ภาพที่ชัดเจนกว่านี้");
  }

  const noteCount = (xml.match(/<note/g) || []).length;
  if (noteCount < 5) throw new Error(`Audiveris only found ${noteCount} notes, falling back...`);
  return {
    xml,
    confidence: noteCount > 20 ? 'high' : 'medium',
    message: `Audiveris อ่านได้ ${noteCount} โน้ต`,
  };
}

/** Returns true if this file should go through image OMR */
export function isImageFile(file: File): boolean {
  return IMAGE_MIME_TYPES.includes(file.type) || /\.(jpg|jpeg|png|webp)$/i.test(file.name);
}

/** Returns true if this file is a PDF */
export function isPDFFile(file: File): boolean {
  return file.type === 'application/pdf' || /\.pdf$/i.test(file.name);
}




export async function recognizeVerificationPass(file: File, draftXml: string): Promise<OCRResult> {
  const isPdf = isPDFFile(file);
  console.log(`[SheetMusicOCR] 🔍 Verification Pass: ${file.name} (${file.type}) | draftXml: ${draftXml.length} chars`);
  
  const base64Data = await fileToBase64(file);
  const mimeType = isPdf ? PDF_MIME_TYPE : ((file.type || 'image/jpeg') as string);

  // Truncate draftXml to prevent exceeding context window
  // A full MusicXML for 8 bars is ~5-10KB; 40000 chars is very generous
  const MAX_DRAFT_CHARS = 40000;
  const safeDraft = draftXml.length > MAX_DRAFT_CHARS 
    ? draftXml.substring(0, MAX_DRAFT_CHARS) + '\n<!-- [TRUNCATED FOR CONTEXT LIMIT] -->'
    : draftXml;

  const rawText = await rateLimitedCallGemini([
    { text: OMR_VERIFY_PROMPT + '\n\n=== DRAFT MUSICXML TO VERIFY ===\n' + safeDraft },
    { inline_data: { mime_type: mimeType, data: base64Data } },
  ]);

  let xml = extractXmlFromGeminiResponse(rawText);
  xml = repairTruncatedXml(xml);

  const noteCount = (xml.match(/<note/g) || []).length;
  console.log(`[SheetMusicOCR] ✅ Verification Pass: ${noteCount} notes in corrected XML`);
  return { xml, confidence: 'high', message: `ตรวจสอบและแก้ไขได้ ${noteCount} โน้ต` };
}
