-- ════════════════════════════════════════════════════════════════
-- Memolody V2 — Supabase Database Initialization & Migration Script
-- ════════════════════════════════════════════════════════════════
-- This script sets up the database schema for authentication profiles, 
-- songs, tokens, rewards, affiliate referrals, and the crowdfunding investor portal.
--
-- Running instructions: Paste this script into the Supabase SQL Editor and run it.

-- ────────────────────────────────────────────────────────────────
-- 1. BASE TABLES & PROFILES
-- ────────────────────────────────────────────────────────────────

-- Profiles Table (Extended user information linked 1:1 with auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT,
    full_name TEXT,
    avatar_url TEXT,
    role TEXT DEFAULT 'member' CHECK (role IN ('member', 'admin')),
    referral_code TEXT UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────
-- 2. CONTENT & SONGS
-- ────────────────────────────────────────────────────────────────

-- Songs Table
CREATE TABLE IF NOT EXISTS public.songs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    artist TEXT,
    music_xml_data JSONB, -- Storing score notations/chords
    lyrics TEXT,
    creator_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL, -- Null if official system song
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.songs ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────
-- 3. TOKENS & TRANSACTION HISTORY
-- ────────────────────────────────────────────────────────────────

-- User Wallets (Token balance)
CREATE TABLE IF NOT EXISTS public.user_wallets (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    balance INTEGER DEFAULT 0 NOT NULL CHECK (balance >= 0),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.user_wallets ENABLE ROW LEVEL SECURITY;

-- Token Transactions Log
CREATE TABLE IF NOT EXISTS public.token_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL, -- positive for credit, negative for debit
    source TEXT NOT NULL CHECK (source IN ('purchase', 'earn_reward', 'ai_generation', 'referral_bonus', 'admin_adjustment', 'seed_bonus')),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.token_transactions ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────
-- 4. PROMOTIONS & REWARDS
-- ────────────────────────────────────────────────────────────────

-- Token Packages for Purchase
CREATE TABLE IF NOT EXISTS public.packages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    token_amount INTEGER NOT NULL CHECK (token_amount > 0),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;

-- Rewards Table
CREATE TABLE IF NOT EXISTS public.rewards (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    token_cost INTEGER NOT NULL CHECK (token_cost > 0),
    stock INTEGER DEFAULT 0 NOT NULL CHECK (stock >= 0),
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.rewards ENABLE ROW LEVEL SECURITY;

-- Reward Claims (Redemption Log)
CREATE TABLE IF NOT EXISTS public.reward_claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reward_id UUID NOT NULL REFERENCES public.rewards(id) ON DELETE RESTRICT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'shipped', 'cancelled')),
    shipping_address TEXT,
    claimed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reward_claims ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────
-- 5. AFFILIATE REFERRAL SYSTEM
-- ────────────────────────────────────────────────────────────────

-- Affiliates / Referrals Table
CREATE TABLE IF NOT EXISTS public.affiliates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    referrer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    referred_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'registered' CHECK (status IN ('registered', 'activated', 'rewarded')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_referral UNIQUE (referrer_id, referred_user_id)
);

ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────
-- 6. CROWDFUNDING & INVESTOR SYSTEM
-- ────────────────────────────────────────────────────────────────

-- Investment Packages
CREATE TABLE IF NOT EXISTS public.investment_packages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    min_amount NUMERIC(12, 2) NOT NULL CHECK (min_amount >= 0),
    tokens_per_month INTEGER DEFAULT 0 NOT NULL,
    revenue_share_percent NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.investment_packages ENABLE ROW LEVEL SECURITY;

-- Investor Profiles
CREATE TABLE IF NOT EXISTS public.investor_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    tier TEXT DEFAULT 'seed' CHECK (tier IN ('seed', 'growth', 'scale')),
    total_invested NUMERIC(12, 2) DEFAULT 0.00 NOT NULL CHECK (total_invested >= 0),
    bank_account_details TEXT,
    is_approved BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.investor_profiles ENABLE ROW LEVEL SECURITY;

-- Individual Investments Record
CREATE TABLE IF NOT EXISTS public.investments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    investor_id UUID NOT NULL REFERENCES public.investor_profiles(id) ON DELETE CASCADE,
    package_id UUID REFERENCES public.investment_packages(id) ON DELETE SET NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'completed', 'rejected')),
    proof_of_transfer_url TEXT,
    invested_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.investments ENABLE ROW LEVEL SECURITY;

-- Financial Reports (Profit/Loss & Dividend Pools)
CREATE TABLE IF NOT EXISTS public.financial_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_revenue NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    net_profit NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    pool_for_dividends NUMERIC(12, 2) DEFAULT 0.00 NOT NULL,
    report_document_url TEXT,
    is_published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.financial_reports ENABLE ROW LEVEL SECURITY;

-- Dividend Payouts to Investors
CREATE TABLE IF NOT EXISTS public.dividend_payouts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID NOT NULL REFERENCES public.financial_reports(id) ON DELETE CASCADE,
    investor_id UUID NOT NULL REFERENCES public.investor_profiles(id) ON DELETE CASCADE,
    payout_amount NUMERIC(12, 2) NOT NULL CHECK (payout_amount >= 0),
    payout_status TEXT DEFAULT 'pending' CHECK (payout_status IN ('pending', 'paid', 'failed')),
    paid_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.dividend_payouts ENABLE ROW LEVEL SECURITY;


-- ────────────────────────────────────────────────────────────────
-- 7. SECURITY & RLS POLICIES
-- ────────────────────────────────────────────────────────────────

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Users can update their own profiles" 
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Songs Policies
CREATE POLICY "Public songs are viewable by everyone" 
    ON public.songs FOR SELECT USING (is_public = true OR auth.uid() = creator_id);

CREATE POLICY "Users can insert their own songs" 
    ON public.songs FOR INSERT WITH CHECK (auth.uid() = creator_id);

CREATE POLICY "Users can update their own songs" 
    ON public.songs FOR UPDATE USING (auth.uid() = creator_id);

CREATE POLICY "Users can delete their own songs" 
    ON public.songs FOR DELETE USING (auth.uid() = creator_id);

-- User Wallets Policies
CREATE POLICY "Users can view their own wallet" 
    ON public.user_wallets FOR SELECT USING (auth.uid() = user_id);

-- Token Transactions Policies
CREATE POLICY "Users can view their own transactions" 
    ON public.token_transactions FOR SELECT USING (auth.uid() = user_id);

-- Packages and Rewards Policies (Publicly viewable)
CREATE POLICY "Packages viewable by everyone" 
    ON public.packages FOR SELECT USING (is_active = true);

CREATE POLICY "Rewards viewable by everyone" 
    ON public.rewards FOR SELECT USING (is_active = true);

-- Reward Claims Policies
CREATE POLICY "Users can view their own claims" 
    ON public.reward_claims FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can make a claim" 
    ON public.reward_claims FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Affiliate Policies
CREATE POLICY "Referrers can view their referral links" 
    ON public.affiliates FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_user_id);

CREATE POLICY "Users can register a referral relationship" 
    ON public.affiliates FOR INSERT WITH CHECK (auth.uid() = referred_user_id);

-- Investor Policies
CREATE POLICY "Investors can view their own investor profile"
    ON public.investor_profiles FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Investors can view their own investments"
    ON public.investments FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.investor_profiles 
            WHERE investor_profiles.id = investments.investor_id 
            AND investor_profiles.user_id = auth.uid()
        )
    );

CREATE POLICY "Investors can register investments"
    ON public.investments FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.investor_profiles 
            WHERE investor_profiles.id = investments.investor_id 
            AND investor_profiles.user_id = auth.uid()
        )
    );

CREATE POLICY "Published financial reports are viewable by approved investors"
    ON public.financial_reports FOR SELECT USING (
        is_published = true AND EXISTS (
            SELECT 1 FROM public.investor_profiles 
            WHERE investor_profiles.user_id = auth.uid() AND investor_profiles.is_approved = true
        )
    );

CREATE POLICY "Investors can view their own payouts"
    ON public.dividend_payouts FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.investor_profiles 
            WHERE investor_profiles.id = dividend_payouts.investor_id 
            AND investor_profiles.user_id = auth.uid()
        )
    );


-- ────────────────────────────────────────────────────────────────
-- 8. AUTOMATION TRIGGERS & FUNCTIONS
-- ────────────────────────────────────────────────────────────────

-- Create Profile & Wallet Trigger when auth.users signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_referral_code TEXT;
BEGIN
    -- Generate a simple unique referral code (substring of UUID)
    v_referral_code := substring(md5(random()::text) from 1 for 8);

    -- Insert into public.profiles
    INSERT INTO public.profiles (id, username, full_name, avatar_url, role, referral_code)
    VALUES (
        NEW.id,
        coalesce(NEW.raw_user_meta_data->>'username', NEW.raw_user_meta_data->>'email'),
        NEW.raw_user_meta_data->>'full_name',
        NEW.raw_user_meta_data->>'avatar_url',
        'member',
        v_referral_code
    );

    -- Initialize wallet with 50 starting tokens
    INSERT INTO public.user_wallets (user_id, balance)
    VALUES (NEW.id, 50);

    -- Log transaction
    INSERT INTO public.token_transactions (user_id, amount, source, description)
    VALUES (NEW.id, 50, 'seed_bonus', 'ยินดีต้อนรับสมาชิกใหม่ แจกโทเค็นเริ่มต้นฟรี');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind the trigger
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
